notifications:
  email: false
  slack:
    rooms:
      secure: mJJaGh4xXg3yAqZ6t/jti6ZFiT5QHM7y+/XI8accp5ipsDYKchfnCFDf5E0+9eGDu74tsNULT4cNio1io2+GcWiGHeNJBEEL9EYAzmqdmpO/ilXBO2bgC8s9m+Sibks+19leJKeEOZ4et04CDf/Xeg2ZiW1G6+O7mHIeDWXcw48MPcoXu7xRZLmsZXKpIoBSVEP1eP/xkTUiYLbgn1dc4wtJFyZRthdxuTBfDBFF+tPTK0uXcxNczdiIPyXRYlncnBzGlhFG28M6htIa7f10JEMrb/3XRDJ4mf5U25CYz9r7+mXOO2RJuuWZRudbN6NQps/81cBDlrLoC5nKMFdWN8MJORHn7b7Q9z1dqj+c3iGq9U80lM1tdbA0i/a1KlQeB0i1YL+NN/WNcNGe4zfH44T6QM631t75EgZXUL3SasK+pkJDAThKib+mm7VACE+pXPPQMPCxHmTaweYxmVUJKsnOaigTF0zKmeGgm0T5LGAmRomGpYAxHxcVVEWCsrO+qVfYdrN7c425UEkSF/2qusp/1+GEp4GaeI8tO78Kn/406wbSt9pbTia/wCWzXf/ivyCETGnH5yrMqU8LxLbavW8mYEcjG/U0x66/1YLHIPALv0xAT9WFRQCKXebwaNJkFwtR1U8zph254+S2nCQ0D/IrfWPY+EnGnVpTsXEwqUI=
    on_success: always
    on_failure: always
stages:
- name: DOC
jobs:
  include:
  - stage: DOC
    os: linux
    language: node_js
    node_js:
    - '16'
    install: true
    script:
    - cd docs && yarn install && yarn build
    - cd .vitepress/dist
    deploy:
      provider: pages
      local-dir: docs/.vitepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
