notifications:
  email: false
  slack:
    rooms:
      secure: Elbdz/lrYnhFSUl7wicATMikfDHmdNFFKZXLR9E2Vunt/YEPra8IN1vsUIWQVZZSG4X2jtVcnvi/fC5ZJfruUAri4hs8Io0h/ccYOfu4Khk9v8SPSOwnV/N8l2QAQorVnnueaRO9IxeOJips+iKBSzDCz/f5ObcgTG3UqMzg2LkW3T6cm6+Fex5QuzokHgbEwdCrxctEiJjVs5dDdsXU2f6KSZER1okF4lqJC02R7QxSeHQm62yuz+e1jbgfQ4b6GCNQyAZkA1ooKZ0aiXBYvQGa15iUj2DuykAw83t3rp5/El4/DEygGw8lYYFSnNj3OsDbfp38zhNXt4BnUBOaGID/2i8hukrcPnbu4lome2QgO6CP3AOUsh9xpXSrQrunZmRIZmWBg7ymbJr90GXdpcLGu9Yx1u6Fr5SkBGKEp/fTb24v02nKI6+dvffNCarDTq9gr36tRhaTi/8drmsqSIE5OooSPRFVjBArCyOpmPcp99kdzbS0Xa7uyT53wx+uaj0Ivq7HlXdI5mGLK56WiJh/Hk8zvdkIezVty2qFISeOhHGremOUpIcGp7COqdOMxcquWQDdzkp4xskjlH1VSVT725pvYZQZZXGjDbFIJowMj83B0rUZTwmzCPMxlHkKK3L1Zj0Sjj1/pZEDNFnSCNmfBWq0+uBGKMwuYuDe6/I=
    on_success: always
    on_failure: always
stages:
- name: DOC
  if: commit_message =~ /\[build doc\]/
jobs:
  include:
  - stage: DOC
    os: linux
    language: node_js
    node_js:
    - '16'
    install: true
    script:
    - yarn install && yarn build
    - cp ./CNAME .vitepress/dist/CNAME
    - cd .vitepress/dist
    deploy:
      provider: pages
      local-dir: .vitepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true